### ISSUE TITLE
How does it work without an API key?

### ISSUE THREAD

**Issue by mkc842** [lminhtm/LMGeocoder#12]
This is amazingly easy to use. I was expecting to have to provide my own `googleAPIKey`. How does it work without one? Am I going to run into problems if I don't provide it? If so, then what if I were using the Apple service? Would I need an API key for that? Thank you!

By the way, here's the swift code I'm using, in case you want to add it:

```
LMGeocoder.sharedInstance().geocodeAddressString(addressString, service: .GoogleService, completionHandler: { (results, error) -> Void in
    if results != nil, let address = results.first as? LMAddress {
        print("Coordinate: (%f, %f)", address.coordinate.latitude, address.coordinate.longitude)
    } else if error != nil {
        print("Geocoding error: \(error.localizedDescription)")
    } else {
        print("No results found")
    }
})
```

**Comment by lminhtm** [comment]
@mkc842 Set googleAPIKey = nil if you don't have your googleAPIKey. There is no problems if you don't provide it.
