### ISSUE TITLE
Original info in LMAddress

### ISSUE THREAD

**Issue by akovalov** [lminhtm/LMGeocoder#18]
Hi! Thanks for really nice component. 
Could you please consider adding full original info into LMAddress object, it could be just dictionary property. So for example I need viewport coordinate received from Google API to show on map, but it's not parsed in LMAddress and there is no ability to access original Google API response. 

I can submit a quick PR for this. 
Thanks.

**Comment by lminhtm** [comment]
Hi! Feel free to make a pull request @akovalov
